
# Create configuration files

!include "allmake.mak"

!ifndef	MAKE_ALL
all:	env
!endif

env:    w32bor.cfg$(CFGSUF) w64bor.cfg$(CFGSUF)

w32bor.cfg$(CFGSUF):     makeenv_br.mak allmake.mak __bor.cfg
        $(CP) __bor.cfg $@
        echo -nbor.w32$(OBJDIRSUF) >>$@
w64bor.cfg$(CFGSUF):     makeenv_br.mak allmake.mak __bor.cfg
        $(CP) __bor.cfg $@
        echo -nbor.w64$(OBJDIRSUF) >>$@

__bor.cfg: makeenv_br.mak allmake.mak
   $(CP) &&|
;this file is generated by make, don't edit
-I$(IDA)include
-I$(BCDIR)include
-L$(IDA)libbor.w32
-L$(BCDIR)lib
;      Alignment 1 byte - for compatibility
-a1
;       Generate for 586
-5
;       No autodependency output
-X
;       Generate fastest code
-O2
;       Force C++ compile
-P
;       Merge duplicate strings
-d
;       Exception handling
-x
-xp
;       Enable RTTI
-RT
;       Multi-thread
-tWM
;       Enable inline functions
-vi
;       No standard stack frame
-k-
;       All warnings on
-w
;       turn off: precision loss
-w-sig
;       turn off: negating unsigned value
-w-ngu
;  off: comparing signed/unsigned values
-w-csu
; Functions containing 'xxx' are not expanded inline
-w-8027
; structure packing size changed
-w-8059
; variable is declared but not used [bcb6 complains about const variables :(]
-w-8080
; template argument xxx passed to 'xxx' is a output iterator: input iterator required in function xxx
-w-8091
; template argument xxx passed to 'xxx' is not an iterator: input iterator required in function xxx
-w-8092
;
-DMAXSTR=1024
-DNO_TV_STREAMS
-D__NT__
;       Output directory
| $@
