PROC=callee
!include ..\plugin.mak

# MAKEDEP dependency list ------------------
$(F)callee$(O): $(I)area.hpp $(I)auto.hpp $(I)bytes.hpp $(I)fpro.h          \
	        $(I)funcs.hpp $(I)help.h $(I)ida.hpp $(I)idp.hpp            \
	        $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp $(I)loader.hpp  \
	        $(I)nalt.hpp $(I)netnode.hpp $(I)pro.h $(I)segment.hpp      \
	        $(I)ua.hpp $(I)xref.hpp callee.cpp
