PROC=subwindow
!include ..\plugin.mak

# MAKEDEP dependency list ------------------
$(F)subwindow$(O): $(I)fpro.h $(I)help.h $(I)ida.hpp $(I)kernwin.hpp         \
	          $(I)llong.hpp $(I)loader.hpp $(I)pro.h subwindow.cpp
